"use client";
import { Inter } from "next/font/google";
import { ChakraProvider } from "@chakra-ui/react";
import Navbar from "@/components/Navbar";
import HeroSection from "@/components/HeroSection";
import Features from "@/components/Features";
import Testimonials from "@/components/Testimonials";
import Footer from "@/components/Footer";
import TweetEmbed from "@/components/TweetEmbed";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ChakraProvider>
          <Navbar/>
          {/* <TweetEmbed/> */}
          <HeroSection/>
          <Features/>
          <Testimonials/>
          <Footer/>
          {/* {children} */}
          </ChakraProvider>
      </body>
    </html>
  );
}
